# Generated by Django 5.0.7 on 2024-11-22 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=200)),
                ('expected_salary', models.CharField(default='Not disclosed', max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('job_desc', models.TextField()),
                ('skills', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=False)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
