# Generated by Django 5.0.7 on 2024-11-22 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_title', models.CharField(default='Empowering Growth', max_length=200)),
                ('company_desc', models.CharField(blank=True, default='', max_length=400)),
                ('founded_year', models.CharField(blank=True, default='', max_length=4)),
                ('company_link', models.URLField(blank=True, default='')),
                ('linkedin_link', models.URLField(blank=True, default='')),
                ('industry', models.CharField(blank=True, default='', max_length=200)),
                ('company_logo', models.ImageField(default='profile_photos/default/profile_image_placeholder.png', upload_to='company_logos/')),
                ('company_background', models.ImageField(default='company_background/default.jpg', upload_to='company_background/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_details', to='accounts.userdetails')),
            ],
        ),
    ]
