# Generated by Django 4.2.18 on 2025-01-16 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_photo', models.ImageField(default='profile_photos/default/profile_image_placeholder.png', upload_to='profile_photos/')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.CharField(blank=True, max_length=500, null=True)),
                ('user_type', models.CharField(default='Seeker', max_length=20)),
                ('languages', models.CharField(blank=True, max_length=500, null=True)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceJourney',
            fields=[
                ('experience_journey_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('experience_type', models.CharField(max_length=255)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_journeys', to='accounts.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='EducationJourney',
            fields=[
                ('education_journey_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=255)),
                ('institute_name', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('course_type', models.CharField(max_length=255)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_journeys', to='accounts.userdetails')),
            ],
        ),
    ]
