# Generated by Django 4.2.21 on 2025-08-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdetails_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationjourney',
            name='grade_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='educationjourney',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationjourney',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='educationjourney',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
