# Generated by Django 4.2.21 on 2025-08-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_educationjourney_grade_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='experience_type',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='experiencejourney',
            name='department',
        ),
        migrations.RemoveField(
            model_name='experiencejourney',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='experiencejourney',
            name='role',
        ),
        migrations.AddField(
            model_name='experiencejourney',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experiencejourney',
            name='course_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experiencejourney',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experiencejourney',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='experiencejourney',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experiencejourney',
            name='total_experience',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='experiencejourney',
            name='university_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experiencejourney',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
