# Generated by Django 4.2.21 on 2025-08-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_experience_type_experiencejourney_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationjourney',
            old_name='user_details',
            new_name='UserDetails',
        ),
        migrations.RenameField(
            model_name='educationjourney',
            old_name='education_journey_id',
            new_name='educationJourneyId',
        ),
        migrations.RenameField(
            model_name='educationjourney',
            old_name='grade_percentage',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='educationjourney',
            old_name='end_year',
            new_name='passingYear',
        ),
        migrations.RenameField(
            model_name='educationjourney',
            old_name='highest_qualification',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='educationjourney',
            old_name='resume_file',
            new_name='resumeUrl',
        ),
        migrations.RenameField(
            model_name='educationjourney',
            old_name='start_year',
            new_name='startYear',
        ),
        migrations.RenameField(
            model_name='educationjourney',
            old_name='institute_name',
            new_name='university',
        ),
        migrations.AddField(
            model_name='educationjourney',
            name='languages',
            field=models.TextField(blank=True, help_text='Comma-separated languages', null=True),
        ),
        migrations.AddField(
            model_name='educationjourney',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills', null=True),
        ),
    ]
