# Generated by Django 4.2.21 on 2025-08-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_user_details_educationjourney_userdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='experience_journey_id',
            new_name='ExperienceJourneyId',
        ),
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='user_details',
            new_name='UserDetails',
        ),
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='company_name',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='course_type',
            new_name='courseType',
        ),
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='end_year',
            new_name='endYear',
        ),
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='highest_qualification',
            new_name='highestQualification',
        ),
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='resume_file',
            new_name='resumeFile',
        ),
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='start_year',
            new_name='startYear',
        ),
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='total_experience',
            new_name='totalExperience',
        ),
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='university_name',
            new_name='universityName',
        ),
    ]
