# Generated by Django 4.2.21 on 2025-08-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_experience_journey_id_experiencejourney_experiencejourneyid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationjourney',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='educationjourney',
            name='skills',
        ),
        migrations.AlterField(
            model_name='educationjourney',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
