# Generated by Django 4.2.21 on 2025-08-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_educationjourney_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
