# Generated by Django 4.2.21 on 2025-08-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userdetails_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='resume',
            new_name='resumeFile',
        ),
    ]
