# Generated by Django 4.2.21 on 2025-08-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_resume_userdetails_resumefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationjourney',
            name='resumeUrl',
        ),
    ]
