# Generated by Django 4.2.21 on 2025-08-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_educationjourney_resumeurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationjourney',
            old_name='UserDetails',
            new_name='userDetails',
        ),
    ]
