# Generated by Django 4.2.21 on 2025-08-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_userdetails_educationjourney_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationjourney',
            old_name='userDetails',
            new_name='userdetails',
        ),
    ]
