# Generated by Django 4.2.21 on 2025-08-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_userdetails_educationjourney_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationjourney',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='educationjourney',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
