# Generated by Django 4.2.21 on 2025-08-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_educationjourney_languages_educationjourney_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='UserDetails',
            new_name='userdetails',
        ),
        migrations.RemoveField(
            model_name='experiencejourney',
            name='resumeFile',
        ),
    ]
