# Generated by Django 4.2.21 on 2025-08-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_userdetails_experiencejourney_userdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencejourney',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='experiencejourney',
            name='designation',
        ),
        migrations.AddField(
            model_name='experiencejourney',
            name='companies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
