# Generated by Django 4.2.21 on 2025-08-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_experiencejourney_companyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencejourney',
            name='skills_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
