# Generated by Django 4.2.21 on 2025-08-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_experiencejourney_skills_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencejourney',
            name='skills',
        ),
    ]
