# Generated by Django 4.2.21 on 2025-08-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_experiencejourney_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencejourney',
            old_name='skills_json',
            new_name='skills',
        ),
    ]
