# Generated by Django 4.2.21 on 2025-08-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_skills_json_experiencejourney_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
